pipeline {
    agent any

    stages {
        stage('Unit Test - Back End') {
            agent {
                docker {
                    image 'golang:1.21'
                    args '-u root'
                }
            }
            steps {
                dir('bugtracker-backend')
                    sh 'go test -v ./...'
            }
        }
    }
}
