pipeline {
    agent any

    stages {
        stage('Unit Test - Back End') {
            agent {
                docker {
                    image 'golang:1.24'
                    reuseNode true
                    args '-u root'
                }
            }
            steps {
                dir('bugtracker-backend') {
                    sh 'go test -v ./...'
                }
            }
        }

        stage('Launch Application') {
            agent {
                docker {
                    image 'docker:27.5.1'
                    reuseNode true
                    args '-v /var/run/docker.sock:/var/run/docker.sock -u 0'
                }
            }
            steps {
                sh 'docker compose up --build -d'
            }
        }
    }
}
